CREATE DATABASE nba_scan;
USE nba_scan;

CREATE TABLE players (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  team VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE stats (
  id INT NOT NULL AUTO_INCREMENT,
  opp VARCHAR(255) NOT NULL,
  bday DATE NOT NULL,
  game_date DATE NOT NULL,
  PpG INT,
  players_id INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (players_id) REFERENCES players(id)
);

CREATE TABLE astro_data (
  id INT NOT NULL AUTO_INCREMENT,
  sun VARCHAR(255) NOT NULL,
  moon VARCHAR(255) NOT NULL,
  mer VARCHAR(255) NOT NULL,
  mars VARCHAR(255) NOT NULL,
  jup VARCHAR(255) NOT NULL,
  stats_id INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (stats_id) REFERENCES stats(id)
)
